# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Install base packages for Jenkins
  become: yes
  ansible.builtin.apt:
    name:
      # Common development tools for Jenkins jobs
      - default-jdk
      - git
      - python3-venv
      # Used by check-outbound-network.service
      - netcat-traditional

- name: dist-upgrade packages
  become: yes
  ansible.builtin.apt:
    upgrade: dist

- name: Clean packages
  become: yes
  ansible.builtin.apt:
    clean: yes

- name: Disable periodic apt tasks
  become: yes
  ansible.builtin.copy:
    src: apt-periodic.conf
    dest: /etc/apt/apt.conf.d/apt-periodic.conf
    owner: root
    group: root
    mode: 0644

- name: Set up /etc/apt/keyrings
  become: yes
  ansible.builtin.file:
    state: directory
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: 0755
