# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Set up Git destination directories
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  loop:
    - /usr/src/arvados
    - /usr/src/arvados.git
    - /usr/local/arvados-dev

# Start a mirror of the arvados repository so Jenkins jobs have less to fetch.
- name: Mirror arvados git repository
  become: yes
  become_user: jenkins
  # ansible.builtin.git does not support the --mirror option
  ansible.builtin.command:
    cmd: git clone --mirror git://git.arvados.org/arvados.git /usr/src/arvados.git
    creates: /usr/src/arvados.git/HEAD

- name: Clone arvados git repository
  become: yes
  become_user: jenkins
  ansible.builtin.git:
    repo: /usr/src/arvados.git
    dest: /usr/src/arvados
    version: "{{ lookup('ansible.builtin.env', 'GIT_HASH', default=omit) }}"

- name: Clone arvados-dev git repository
  become: yes
  become_user: jenkins
  ansible.builtin.git:
    repo: git://git.arvados.org/arvados-dev.git
    dest: /usr/local/arvados-dev
