# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Wait for cloud-init to finish its work
  ansible.builtin.command:
    cmd: cloud-init status --wait
  # Maybe cloud-init isn't installed, maybe it really failed.
  # Either way, we want to go ahead with the rest of the playbook.
  failed_when: "false"

- name: Bootstrap packages required for Ansible
  become: yes
  ansible.builtin.raw: "apt-get -o DPkg::Lock::Timeout=300 -qy {{ item }}"
  loop:
    - update
    - install acl gnupg python3-apt python3-debian xz-utils

- ansible.builtin.import_tasks: apt.yml
- ansible.builtin.import_tasks: node_ready.yml
- ansible.builtin.import_tasks: user.yml
- ansible.builtin.import_tasks: git_clones.yml
