# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Install check-outbound-network.service
  become: yes
  ansible.builtin.copy:
    src: check-outbound-network.service
    dest: /etc/systemd/system/check-outbound-network.service
    owner: root
    group: root
    mode: 0644
  register: check_outbound_network_service

- name: Enable check-outbound-network.service
  become: yes
  ansible.builtin.systemd_service:
    name: check-outbound-network.service
    enabled: true
    daemon_reload: "{{ check_outbound_network_service.changed }}"

# This script manually did the work of check-outbound-network.service.
# Make a stub so Jenkins configuration that refers to it still works.
- name: Make node-ready.sh stub
  become: yes
  ansible.builtin.file:
    path: /usr/local/bin/node-ready.sh
    state: link
    src: /usr/bin/true
