# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

- name: Create jenkins user
  become: yes
  ansible.builtin.user:
    name: jenkins
  register: jenkins_user

- name: Create Jenkins tmp directory
  become: yes
  ansible.builtin.file:
    path: "{{ (jenkins_user.home, 'tmp')|path_join }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
