# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# This playbook sets up a minimal node to run test-provision.

- hosts: all
  tasks:
    - ansible.builtin.include_role:
        name: jenkins_base
    - ansible.builtin.include_role:
        name: ci_ansible
      # Arvados tools require at least Ansible 8, which in turn requires
      # Python 3.9+. Don't install it if we don't have that. This is okay
      # because the provision nodes aren't using Ansible *yet*, and these
      # older distributions (namely Ubuntu 20.04) probably never will.
      when: "ansible_python_version is version('3.9.0', operator='>=')"
